version: '3'

services:
  db:
    image: postgres
    container_name: formbuilder_db
    restart: always
    ports:
      - "${DB_PORT}:5432"
    volumes:
      - ./data/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DBNAME}
    networks:
      - my_network

  web:
    container_name: formbuilder_web
    restart: always
    build: 
      context: frontend
      dockerfile: Dockerfile
    ports:
      - "${WEB_PORT}:5173"
    volumes:
      - /home/node/app/node_modules
      - ./frontend:/home/node/app
    environment:
      - VITE_API_URL=http://localhost:${API_PORT}/api
    links:
      - api
    stdin_open: true
    networks:
      my_network:
        aliases:
          - frontend

  api:
    container_name: formbuilder_api
    restart: always
    build:
      context: backend
      dockerfile: Dockerfile
    environment:
      - DB_NAME=${POSTGRES_DBNAME}
      - DB_USER=${POSTGRES_USER}
      - DB_PASSWORD=${POSTGRES_PASSWORD}
      - DB_HOST=db
      - DB_PORT=${DB_PORT}
      - SECRET_KEY=${SECRET_KEY}
    ports:
      - "${API_PORT}:8000"
    volumes:
      - ./backend:/usr/src/app
    command: python manage.py runserver 0.0.0.0:8000
    depends_on:
      - db
    networks:
      my_network:
        aliases:
          - api
    
  nginx:
    container_name: formbuilder_nginx
    restart: always
    build:
      context: nginx
      dockerfile: Dockerfile
    ports:
      - "${NGINX_PORT}:80"
    depends_on:
      - api
      - web

networks:
  my_network:
    driver: bridge