version: '3'

services:
  db:
    image: postgres
    container_name: formbuilder_db
    restart: always
    ports:
      - "${DB_PORT}:5432"
    volumes:
      - ./data/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DBNAME}
    networks:
      - my_network

  web:
    build:
      context: frontend
      dockerfile: Dockerfile
    container_name: formbuilder_web
    restart: always
    ports:
      - "${WEB_PORT}:5173"
    volumes:
      - ./frontend:/app/reactapp
    environment:
      - NODE_ENV=development
      - API_PORT=${API_PORT}
    networks:
      my_network:
        aliases:
          - frontend
    stdin_open: true

  api:
    build:
      context: backend
      dockerfile: Dockerfile
    container_name: formbuilder_api
    restart: always
    ports:
      - "${API_PORT}:8000"
    volumes:
      - ./backend:/app/backend
    depends_on:
      - db
    environment:
      - DB_NAME=${POSTGRES_DBNAME}
      - DB_USER=${POSTGRES_USER}
      - DB_PASSWORD=${POSTGRES_PASSWORD}
      - DB_HOST=db
      - DB_PORT=${DB_PORT}
      - SECRET_KEY=${SECRET_KEY}
    networks:
      my_network:
        aliases:
          - api
    
  nginx:
    container_name: formbuilder_nginx
    restart: always
    build:
      context: nginx
      dockerfile: Dockerfile
    ports:
      - "${NGINX_PORT}:80"
    depends_on:
      - api
      - web

networks:
  my_network:
    driver: bridge