# Generated by Django 4.1.13 on 2024-04-28 04:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Form',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=40)),
                ('authorized_users', models.ManyToManyField(blank=True, related_name='authorized_forms', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='FormSettings',
            fields=[
                ('form', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='form.form')),
                ('question_number_shape', models.CharField(max_length=10)),
                ('question_number_shape_size', models.IntegerField(default=35)),
                ('question_number_shape_type', models.CharField(max_length=10)),
                ('question_number_shape_color', models.CharField(max_length=7)),
                ('question_number_color', models.CharField(max_length=7)),
                ('question_statement_color', models.CharField(max_length=7)),
                ('show_question_bottom_border', models.BooleanField(default=True)),
                ('show_alternative_marker', models.BooleanField(default=True)),
                ('alternative_marker', models.CharField(max_length=10)),
                ('alternative_checkmark', models.CharField(max_length=10)),
                ('question_bottom_border_color', models.CharField(max_length=7)),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveSmallIntegerField(default=1)),
                ('statement', models.CharField(max_length=200)),
                ('type', models.CharField(choices=[('TX', 'Text Question'), ('MC', 'Multiple Choice'), ('MS', 'Multiple Selection')], max_length=3)),
                ('open_question_answer', models.TextField(blank=True)),
                ('form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='form.form')),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/')),
                ('alt_name', models.CharField(max_length=40)),
                ('position', models.CharField(choices=[(1, 'left'), (2, 'center'), (3, 'right')], max_length=7)),
                ('area', models.PositiveSmallIntegerField(choices=[(1, '1/3'), (2, '2/3'), (3, '3/3')])),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='form.question')),
            ],
        ),
        migrations.CreateModel(
            name='FormAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_responses', to='form.form')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='form_answers', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Alternative',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('detail', models.CharField(max_length=200)),
                ('is_correct', models.BooleanField(default=False)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alternatives', to='form.question')),
            ],
        ),
    ]
