# Generated by Django 4.1.5 on 2023-01-18 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='text',
            field=models.CharField(default='dsdsd', max_length=200),
            preserve_default=False,
        ),
    ]
