# Generated by Django 4.1.6 on 2023-02-14 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='form',
            name='title',
            field=models.CharField(max_length=40),
        ),
    ]
