# Generated by Django 4.1.5 on 2023-01-18 09:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0003_remove_question_type_multiplechoosequestion_type_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='text',
            new_name='question_text',
        ),
    ]
