# Generated by Django 4.1.5 on 2023-01-30 21:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0004_rename_text_question_question_text'),
    ]

    operations = [
        migrations.CreateModel(
            name='FillBlank',
            fields=[
                ('question_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='form.question')),
                ('type', models.CharField(default='TX', max_length=3)),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('form.question',),
        ),
        migrations.CreateModel(
            name='TrueFalse',
            fields=[
                ('question_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='form.question')),
                ('type', models.CharField(default='TF', max_length=3)),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('form.question',),
        ),
        migrations.RenameModel(
            old_name='MultipleChooseQuestion',
            new_name='MultipleChoice',
        ),
        migrations.RemoveField(
            model_name='alternative',
            name='question',
        ),
        migrations.DeleteModel(
            name='TextQuestion',
        ),
        migrations.AddField(
            model_name='truefalse',
            name='alternatives',
            field=models.ManyToManyField(to='form.alternative'),
        ),
        migrations.AddField(
            model_name='fillblank',
            name='alternatives',
            field=models.ManyToManyField(to='form.alternative'),
        ),
    ]
